# Generated by Django 4.2.29 on 2026-09-22 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor_nombre', models.CharField(blank=True, default='', max_length=150)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.DateTimeField(auto_now_add=True)),
                ('hora_salida', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('caja_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('ventas_dia', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_entregado', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('faltante', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['vendedor', 'fecha'], name='idx_turno_vendedor_fecha'), models.Index(fields=['estado'], name='idx_turno_estado')],
            },
        ),
    ]
