# Generated by Django 4.2.29 on 2026-09-22 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='hora_entrada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
