# Generated by Django 4.2.29 on 2026-05-30 18:21

from django.db import migrations, models


def set_existing_users_email_verified(apps, schema_editor):
    Usuario = apps.get_model('usuarios', 'Usuario')
    Usuario.objects.filter(email_verified=False).update(
        email_verified=True,
        email_verification_code='',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email_verification_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_existing_users_email_verified, reverse_code=migrations.RunPython.noop),
    ]
