# Generated by Django 4.2.30 on 2026-06-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_add_email_verification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='otp',
            new_name='otps_usuario_2f7071_idx',
            old_name='otps_usuario_codigo_tipo_idx',
        ),
    ]
