# Generated by Django 4.2.30 on 2026-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('vendedor_2', 'Vendedor 2'), ('gerente', 'Gerente'), ('auditor', 'Auditor')], default='vendedor', max_length=10),
        ),
    ]
