# Generated by Django 4.2.7 on 2026-03-29 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Libro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("nit", models.CharField(max_length=50)),
                ("anio", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Libro Fiscal",
                "verbose_name_plural": "Libros Fiscales",
                "db_table": "libro",
                "ordering": ["-anio", "nombre"],
            },
        ),
        migrations.AddConstraint(
            model_name="libro",
            constraint=models.UniqueConstraint(
                fields=("nit", "anio"), name="uniq_libro"
            ),
        ),
        migrations.AddConstraint(
            model_name="libro",
            constraint=models.UniqueConstraint(
                fields=("nombre", "anio"), name="uniq_libro_nombre_anio"
            ),
        ),
    ]
