# Generated by Django 4.2.29 on 2026-08-28 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoControl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del punto de control', max_length=255)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del punto de control', null=True)),
                ('tipo', models.CharField(choices=[('base_datos', 'Base de Datos'), ('configuracion', 'Configuración'), ('completo', 'Completo')], default='completo', help_text='Tipo de respaldo realizado', max_length=20)),
                ('estado', models.CharField(choices=[('completado', 'Completado'), ('en_proceso', 'En Proceso'), ('fallido', 'Fallido')], default='en_proceso', help_text='Estado actual del respaldo', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del respaldo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, help_text='Última fecha de modificación')),
                ('fecha_restauracion', models.DateTimeField(blank=True, help_text='Fecha de la última restauración', null=True)),
                ('tamano_archivo', models.BigIntegerField(default=0, help_text='Tamaño del archivo de respaldo en bytes')),
                ('ruta_archivo', models.CharField(blank=True, help_text='Ruta del archivo de respaldo', max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional del respaldo en formato JSON')),
                ('es_automatico', models.BooleanField(default=False, help_text='Indica si el respaldo fue creado automáticamente')),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que creó el respaldo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_restaurador', models.ForeignKey(blank=True, help_text='Usuario que restauró el respaldo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_restaurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Control',
                'verbose_name_plural': 'Puntos de Control',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroRestauracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la restauración')),
                ('duracion_segundos', models.FloatField(blank=True, help_text='Duración de la restauración en segundos', null=True)),
                ('exitoso', models.BooleanField(default=True, help_text='Indica si la restauración fue exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la restauración falló', null=True)),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la restauración', null=True)),
                ('punto_control', models.ForeignKey(help_text='Punto de control que fue restaurado', on_delete=django.db.models.deletion.CASCADE, related_name='registros_restauracion', to='respaldo.puntocontrol')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó la restauración', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Restauración',
                'verbose_name_plural': 'Registros de Restauración',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='respaldo_re_fecha_6fdcaa_idx'), models.Index(fields=['punto_control'], name='respaldo_re_punto_c_848835_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['-fecha_creacion'], name='respaldo_pu_fecha_c_b864a3_idx'),
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['estado'], name='respaldo_pu_estado_7f28f1_idx'),
        ),
        migrations.AddIndex(
            model_name='puntocontrol',
            index=models.Index(fields=['tipo'], name='respaldo_pu_tipo_e61401_idx'),
        ),
    ]
