# Generated by Django 4.2.29 on 2026-09-07 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movimientos', '0003_movimiento_es_compilacion_ventas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0002_libro_propietario_and_scoped_uniques'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'providers',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion_producto', models.CharField(max_length=255)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_pagado', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='libros.libro')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='movimientos.movimiento')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finanzas.provider')),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Diario'), ('monthly', 'Mensual')], max_length=10)),
                ('period_start', models.DateField()),
                ('total_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cantidad_ventas', models.PositiveIntegerField(default=0)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_stats',
                'indexes': [models.Index(fields=['period', 'period_start'], name='seller_stat_period_17605d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='sellerstats',
            constraint=models.UniqueConstraint(fields=('vendedor', 'period', 'period_start'), name='uniq_seller_stats_period'),
        ),
    ]
