# Generated by Django 4.2.30 on 2026-09-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_desactivar_proveedores_no_deseados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='expense',
            name='valor_pagado',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='expense',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellerstats',
            name='ticket_promedio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='sellerstats',
            name='total_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
