# Generated by Django 4.2.30 on 2026-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('nit', models.CharField(max_length=50, unique=True)),
                ('telefono', models.CharField(blank=True, default='', max_length=40)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
                'ordering': ['nombre', 'id'],
            },
        ),
    ]
