# Generated by Django 4.2.30 on 2026-09-23 22:03

from django.db import migrations, models


def populate_nit_normalizado(apps, schema_editor):
    Cliente = apps.get_model("clientes", "Cliente")
    for cliente in Cliente.objects.all().iterator():
        normalized = "".join(character for character in cliente.nit.strip().upper() if character.isalnum())
        cliente.nit_normalizado = normalized
        cliente.save(update_fields=["nit_normalizado"])


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='nit_normalizado',
            field=models.CharField(editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(populate_nit_normalizado, migrations.RunPython.noop),
    ]
