# Generated by Django 4.2.7 on 2026-03-29 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("libros", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movimiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.CharField(max_length=255)),
                ("nombre", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ingresos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "egresos",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "libro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="libros.libro",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento",
                "verbose_name_plural": "Movimientos",
                "db_table": "movimientos",
                "ordering": ["fecha", "id"],
                "indexes": [
                    models.Index(fields=["libro"], name="idx_mov_libro"),
                    models.Index(
                        fields=["nombre", "fecha"], name="idx_mov_nombre_fecha"
                    ),
                ],
            },
        ),
    ]
