# Generated by Django 4.2.29 on 2026-09-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0002_movimiento_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='es_compilacion_ventas',
            field=models.BooleanField(default=False),
        ),
    ]
