# Generated by Django 4.2.30 on 2026-09-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0003_movimiento_es_compilacion_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='egresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='ingresos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
