# Generated by Django 4.2.29 on 2026-09-01 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0004_producto_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_venta', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('cantidad_productos', models.IntegerField(default=0)),
                ('cantidad_total_unidades', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_costo', models.DecimalField(decimal_places=2, default=0, help_text='Costo total de productos vendidos', max_digits=14)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, help_text='Monto de ganancia (total - costo)', max_digits=14)),
                ('margen_ganancia', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de ganancia', max_digits=5)),
                ('cliente', models.CharField(blank=True, default='', max_length=180)),
                ('medio_pago', models.CharField(blank=True, default='', max_length=20)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('dispositivo', models.CharField(blank=True, default='', max_length=255)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_ventas_detallado', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_venta', to='inventario.venta')),
            ],
            options={
                'db_table': 'inventario_historial_ventas',
                'ordering': ['-fecha_venta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada de Stock'), ('venta', 'Venta'), ('ajuste', 'Ajuste Manual'), ('devolucion', 'Devolución'), ('perdida', 'Pérdida/Daño')], max_length=20)),
                ('cantidad_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_movida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('razon', models.CharField(blank=True, default='', help_text='Razón del movimiento', max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_usuario', models.GenericIPAddressField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_inventario', to='inventario.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_movimientos', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, help_text='Si el movimiento es una venta, aquí se registra el vendedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_realizadas_historial', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_movimientos', to='inventario.venta')),
            ],
            options={
                'db_table': 'inventario_historial_inventario',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EstadoInventarioCentralizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('es_critico', models.BooleanField(default=False, help_text='Indica si el stock está por debajo del mínimo')),
                ('notificacion_enviada', models.BooleanField(default=False, help_text='Si ya se envió notificación por stock bajo')),
                ('version', models.BigIntegerField(default=0, help_text='Versión para control de concurrencia optimista')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estado_centralizado', to='inventario.producto')),
                ('usuario_actualizo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualizaciones_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estado Centralizado',
                'verbose_name_plural': 'Estados Centralizados',
                'db_table': 'inventario_estado_centralizado',
            },
        ),
        migrations.CreateModel(
            name='ResumenVentasPorVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, db_index=True)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('cantidad_unidades', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('monto_costo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ganancia_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margen_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumen_ventas_diarias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventario_resumen_ventas_vendedor',
                'ordering': ['-fecha', 'vendedor'],
                'indexes': [models.Index(fields=['vendedor', '-fecha'], name='inventario__vendedo_3a848d_idx'), models.Index(fields=['-fecha'], name='inventario__fecha_e4cb4d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='resumenventasporvendedor',
            constraint=models.UniqueConstraint(fields=('vendedor', 'fecha'), name='uniq_resumen_vendedor_fecha'),
        ),
        migrations.AddIndex(
            model_name='historialventas',
            index=models.Index(fields=['vendedor', '-fecha_venta'], name='inventario__vendedo_cbdf46_idx'),
        ),
        migrations.AddIndex(
            model_name='historialventas',
            index=models.Index(fields=['-fecha_venta'], name='inventario__fecha_v_3b3d5d_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinventario',
            index=models.Index(fields=['-fecha', 'producto'], name='inventario__fecha_1d2c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinventario',
            index=models.Index(fields=['usuario', '-fecha'], name='inventario__usuario_0be1b1_idx'),
        ),
        migrations.AddIndex(
            model_name='historialinventario',
            index=models.Index(fields=['tipo_movimiento', '-fecha'], name='inventario__tipo_mo_9c7d0a_idx'),
        ),
    ]
