# Generated by Django 4.2.29 on 2026-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_historialventas_historialinventario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana (06:00 - 14:00)'), ('tarde', 'Tarde (14:00 - 22:00)'), ('noche', 'Noche (22:00 - 06:00)')], default='mañana', max_length=10),
        ),
    ]
