# Generated by Django 4.2.29 on 2026-09-03 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_propietario_and_scoped_uniques'),
        ('inventario', '0006_venta_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='libro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='libros.libro'),
        ),
    ]
