# Generated by Django 4.2.30 on 2026-09-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0012_venta_cliente_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='clientes.cliente'),
        ),
    ]
